#!/usr/bin/env bash
# (new ubuntu machine configuration by) installing
# nginx listening on port 80
# serve page returning a Hello World string

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# start nginx service
sudo service nginx start

# allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# give user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# default index backup
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# new index creation
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# restart nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
