#!/usr/bin/env bash
# new ubuntu machine configuration -
# by installing nginx listening on port 80
# with redirect set-up
# server page returning Hello World string


echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# start nginx service
sudo service nginx start

# allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# give ownership of website files to user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# default index back-up
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# new index creation
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# set up /redirect_me to youtube
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
