#!/usr/bin/env bash
# prints "Best school" 10 times - "hi" on 9th cycle/iteration

n=1

while [ $n -le 10 ]
do
    echo "Best School"
    if [ $n -eq 9 ]
    then
        echo "Hi"
    fi
    n=$(( n + 1 ))
done
